name: keck_pypeit
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pyyaml>=5.1
  - requests>=2.23
  - packaging>=19.0
  - scikit-learn>=0.20
  - setuptools>=46.4
  - matplotlib>=3.1
  - configobj>=5.0.6
  - ipython>=7.2
  - extension-helpers>=0.1
  - ginga>=3.0
  - qtpy>=1.9
  - bottleneck
  - linetools>=0.3dev2231
  - scikit-image~=0.16.2
  - astropy~=4.0 
  - conda-forge::ccdproc~=2.2.0
  - numpy~=1.20
  - scipy~=1.4.1
  - pyerfa
  - bokeh~=2.0.0
  - psutil~=5.7.0
  - pandas~=1.0.3
  - conda-forge::selenium
  - conda-forge::geckodriver
  - conda-forge::firefox
  - conda-forge::phantomjs
  - astropy::pyregion
  - pytest~=5.4.1
  - cython
  - conda-forge::pypeit
  - pip
  - pip:
    - ref_index~=1.0
    - keckdrpframework
